### ISSUE TITLE
serial read - serial write

### ISSUE THREAD

**Issue by yo2ldk** [EdwinCroissantArduinoLibraries/SimpleNextion#1]
Hi Edwin,
nice work with this library, congratulations for your work!
 Because I am more hardware man instead software, please help me with some tips (code) ;
 I need to read some values with arduino from a device on serial 1 to say, and that put in on serial 2 on Nextion text that value.
 case is this: an FM receiver on 108.8 Mhz send this frequency value via serial (hex value) to arduino module, and I want to read it on Nextion display. 
  If frequency is changed, that need to be also on display
Hope i write clear what I need, Thank you in advance for your time and support !

**Comment by EdwinCroissant** [comment]
I am sorry, I missed this one as I have little experience with Github :)
It should be doable, receiving data on one serial port, process it and forward it to the Nextion on another serial port and I think this question is more appropriate on one of the Arduino of Nextion forums.
